/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/cross/workspace/djondb/db/grammars/filter_expression.g
 *     -                            On : 2012-08-07 17:44:38
 *     -                for the parser : filter_expressionParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "filter_expressionParser.h"

static void displayRecognitionErrorNew  (pANTLR3_BASE_RECOGNIZER recognizer, pANTLR3_UINT8 * tokenNames) throw(ParseException)
{ 
/*
    switch (recognizer->state->exception->type) {
    	case ANTLR3_UNWANTED_TOKEN_EXCEPTION:
		break;
	default:
		throw ParseException(1, (char*)recognizer->state->exception->message);
    }
    */
}
static void reportOverride(pANTLR3_BASE_RECOGNIZER recognizer) {
}
 
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pfilter_expressionParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pfilter_expressionParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pfilter_expressionParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pfilter_expressionParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   filter_expressionParserTokenNames[25+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "DOLLAR",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "EXPONENT",
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "HEX_DIGIT",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "LBRAK",
        (pANTLR3_UINT8) "LBRAN",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "OCTAL_ESC",
        (pANTLR3_UINT8) "OPER",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "RBRAK",
        (pANTLR3_UINT8) "RBRAN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "SEMICOLON",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "UNICODE_ESC",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "XPATH"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 BaseExpression*
	start_point    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	filter_expr    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	boolean_expr    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	boolean_term    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	boolean_value    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	parenthesized_boolean    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	nonparentherized_boolean    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	unary_expr    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	xpath_expr    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	constant_expr    (pfilter_expressionParser ctx);
static 
 BaseExpression*
	operand_expr    (pfilter_expressionParser ctx);
static void	filter_expressionParserFree(pfilter_expressionParser ctx);
static void     filter_expressionParserReset (pfilter_expressionParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/cross/workspace/djondb/db/grammars/filter_expression.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new filter_expressionParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pfilter_expressionParser
filter_expressionParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return filter_expressionParserNewSSD(instream, NULL);
}

/** \brief Create a new filter_expressionParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pfilter_expressionParser
filter_expressionParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pfilter_expressionParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pfilter_expressionParser) ANTLR3_CALLOC(1, sizeof(filter_expressionParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in filter_expressionParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our filter_expressionParser interface
     */
    ctx->start_point	= start_point;
    ctx->filter_expr	= filter_expr;
    ctx->boolean_expr	= boolean_expr;
    ctx->boolean_term	= boolean_term;
    ctx->boolean_value	= boolean_value;
    ctx->parenthesized_boolean	= parenthesized_boolean;
    ctx->nonparentherized_boolean	= nonparentherized_boolean;
    ctx->unary_expr	= unary_expr;
    ctx->xpath_expr	= xpath_expr;
    ctx->constant_expr	= constant_expr;
    ctx->operand_expr	= operand_expr;
    ctx->free			= filter_expressionParserFree;
    ctx->reset			= filter_expressionParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */


     RECOGNIZER->displayRecognitionError       = displayRecognitionErrorNew;
    // RECOGNIZER->reportError = reportOverride;
    //  RECOGNIZER->antlr3RecognitionExceptionNew = antlr3RecognitionExceptionNewNew;
    //  RECOGNIZER->mismatch                      = mismatchNew;

    /* Install the token table
     */
    PSRSTATE->tokenNames   = filter_expressionParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
filter_expressionParserReset (pfilter_expressionParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 filter_expressionParserFree(pfilter_expressionParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return filter_expressionParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_filter_expr_in_start_point69  */
static	ANTLR3_BITWORD FOLLOW_filter_expr_in_start_point69_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_filter_expr_in_start_point69	= { FOLLOW_filter_expr_in_start_point69_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start_point71  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start_point71_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start_point71	= { FOLLOW_EOF_in_start_point71_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_expr_in_filter_expr89  */
static	ANTLR3_BITWORD FOLLOW_boolean_expr_in_filter_expr89_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_expr_in_filter_expr89	= { FOLLOW_boolean_expr_in_filter_expr89_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_term_in_boolean_expr107  */
static	ANTLR3_BITWORD FOLLOW_boolean_term_in_boolean_expr107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100002) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_term_in_boolean_expr107	= { FOLLOW_boolean_term_in_boolean_expr107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OR_in_boolean_expr115  */
static	ANTLR3_BITWORD FOLLOW_OR_in_boolean_expr115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000012012000) };
static  ANTLR3_BITSET_LIST FOLLOW_OR_in_boolean_expr115	= { FOLLOW_OR_in_boolean_expr115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_term_in_boolean_expr119  */
static	ANTLR3_BITWORD FOLLOW_boolean_term_in_boolean_expr119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100002) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_term_in_boolean_expr119	= { FOLLOW_boolean_term_in_boolean_expr119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_value_in_boolean_term138  */
static	ANTLR3_BITWORD FOLLOW_boolean_value_in_boolean_term138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_value_in_boolean_term138	= { FOLLOW_boolean_value_in_boolean_term138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_in_boolean_term146  */
static	ANTLR3_BITWORD FOLLOW_AND_in_boolean_term146_bits[]	= { ANTLR3_UINT64_LIT(0x0000000012012000) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_in_boolean_term146	= { FOLLOW_AND_in_boolean_term146_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_value_in_boolean_term150  */
static	ANTLR3_BITWORD FOLLOW_boolean_value_in_boolean_term150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000012) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_value_in_boolean_term150	= { FOLLOW_boolean_value_in_boolean_term150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_parenthesized_boolean_in_boolean_value170  */
static	ANTLR3_BITWORD FOLLOW_parenthesized_boolean_in_boolean_value170_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_parenthesized_boolean_in_boolean_value170	= { FOLLOW_parenthesized_boolean_in_boolean_value170_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_nonparentherized_boolean_in_boolean_value177  */
static	ANTLR3_BITWORD FOLLOW_nonparentherized_boolean_in_boolean_value177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_nonparentherized_boolean_in_boolean_value177	= { FOLLOW_nonparentherized_boolean_in_boolean_value177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_parenthesized_boolean193  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_parenthesized_boolean193_bits[]	= { ANTLR3_UINT64_LIT(0x0000000012012000) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_parenthesized_boolean193	= { FOLLOW_LPAREN_in_parenthesized_boolean193_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_boolean_expr_in_parenthesized_boolean195  */
static	ANTLR3_BITWORD FOLLOW_boolean_expr_in_parenthesized_boolean195_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_boolean_expr_in_parenthesized_boolean195	= { FOLLOW_boolean_expr_in_parenthesized_boolean195_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_parenthesized_boolean199  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_parenthesized_boolean199_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_parenthesized_boolean199	= { FOLLOW_RPAREN_in_parenthesized_boolean199_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_unary_expr_in_nonparentherized_boolean215  */
static	ANTLR3_BITWORD FOLLOW_unary_expr_in_nonparentherized_boolean215_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080002) };
static  ANTLR3_BITSET_LIST FOLLOW_unary_expr_in_nonparentherized_boolean215	= { FOLLOW_unary_expr_in_nonparentherized_boolean215_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OPER_in_nonparentherized_boolean221  */
static	ANTLR3_BITWORD FOLLOW_OPER_in_nonparentherized_boolean221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000012002000) };
static  ANTLR3_BITSET_LIST FOLLOW_OPER_in_nonparentherized_boolean221	= { FOLLOW_OPER_in_nonparentherized_boolean221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_unary_expr_in_nonparentherized_boolean225  */
static	ANTLR3_BITWORD FOLLOW_unary_expr_in_nonparentherized_boolean225_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080002) };
static  ANTLR3_BITSET_LIST FOLLOW_unary_expr_in_nonparentherized_boolean225	= { FOLLOW_unary_expr_in_nonparentherized_boolean225_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_constant_expr_in_unary_expr255  */
static	ANTLR3_BITWORD FOLLOW_constant_expr_in_unary_expr255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_constant_expr_in_unary_expr255	= { FOLLOW_constant_expr_in_unary_expr255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_xpath_expr_in_unary_expr263  */
static	ANTLR3_BITWORD FOLLOW_xpath_expr_in_unary_expr263_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_xpath_expr_in_unary_expr263	= { FOLLOW_xpath_expr_in_unary_expr263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_XPATH_in_xpath_expr280  */
static	ANTLR3_BITWORD FOLLOW_XPATH_in_xpath_expr280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_XPATH_in_xpath_expr280	= { FOLLOW_XPATH_in_xpath_expr280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_constant_expr296  */
static	ANTLR3_BITWORD FOLLOW_INT_in_constant_expr296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_constant_expr296	= { FOLLOW_INT_in_constant_expr296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_constant_expr303  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_constant_expr303_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_constant_expr303	= { FOLLOW_STRING_in_constant_expr303_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OPER_in_operand_expr318  */
static	ANTLR3_BITWORD FOLLOW_OPER_in_operand_expr318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_OPER_in_operand_expr318	= { FOLLOW_OPER_in_operand_expr318_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start start_point
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:47:1: start_point returns [BaseExpression* val] : filter_expr EOF ;
 */
static BaseExpression*
start_point(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* filter_expr1;
    #undef	RETURN_TYPE_filter_expr1
    #define	RETURN_TYPE_filter_expr1 BaseExpression*

    /* Initialize rule variables
     */


    	
    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:49:4: ( filter_expr EOF )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:49:6: filter_expr EOF
        {
            FOLLOWPUSH(FOLLOW_filter_expr_in_start_point69);
            filter_expr1=filter_expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestart_pointEx;
            }


             MATCHT(EOF, &FOLLOW_EOF_in_start_point71);
            if  (HASEXCEPTION())
            {
                goto rulestart_pointEx;
            }


            {

                	    val= 
                filter_expr1
                ;

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestart_pointEx; /* Prevent compiler warnings */
    rulestart_pointEx: ;



    return val;
}
/* $ANTLR end start_point */

/**
 * $ANTLR start filter_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:54:1: filter_expr returns [BaseExpression* val] : boolean_expr ;
 */
static BaseExpression*
filter_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* boolean_expr2;
    #undef	RETURN_TYPE_boolean_expr2
    #define	RETURN_TYPE_boolean_expr2 BaseExpression*

    /* Initialize rule variables
     */

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:55:2: ( boolean_expr )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:56:2: boolean_expr
        {
            FOLLOWPUSH(FOLLOW_boolean_expr_in_filter_expr89);
            boolean_expr2=boolean_expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefilter_exprEx;
            }


            {

                	val= 
                boolean_expr2
                ;

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefilter_exprEx; /* Prevent compiler warnings */
    rulefilter_exprEx: ;



    return val;
}
/* $ANTLR end filter_expr */

/**
 * $ANTLR start boolean_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:60:1: boolean_expr returns [BaseExpression* val] : b1= boolean_term ( OR b2= boolean_term )* ;
 */
static BaseExpression*
boolean_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* b1;
    #undef	RETURN_TYPE_b1
    #define	RETURN_TYPE_b1 BaseExpression*

    BaseExpression* b2;
    #undef	RETURN_TYPE_b2
    #define	RETURN_TYPE_b2 BaseExpression*

    /* Initialize rule variables
     */

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:61:2: (b1= boolean_term ( OR b2= boolean_term )* )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:61:4: b1= boolean_term ( OR b2= boolean_term )*
        {
            FOLLOWPUSH(FOLLOW_boolean_term_in_boolean_expr107);
            b1=boolean_term(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleboolean_exprEx;
            }


            {

                	   val= 
                b1
                ;

                	
            }


            // /home/cross/workspace/djondb/db/grammars/filter_expression.g:65:2: ( OR b2= boolean_term )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case OR:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:65:3: OR b2= boolean_term
            	    {
            	         MATCHT(OR, &FOLLOW_OR_in_boolean_expr115);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleboolean_exprEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_boolean_term_in_boolean_expr119);
            	        b2=boolean_term(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleboolean_exprEx;
            	        }


            	        {

            	            	   BinaryExpression* be = new BinaryExpression(FO_OR);
            	            	   be->push(val
            	            );
            	            	   be->push(b2
            	            );
            	            	   val= be;

            	            	
            	        }


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleboolean_exprEx; /* Prevent compiler warnings */
    ruleboolean_exprEx: ;



    return val;
}
/* $ANTLR end boolean_expr */

/**
 * $ANTLR start boolean_term
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:72:1: boolean_term returns [BaseExpression* val] : b1= boolean_value ( AND b2= boolean_value )* ;
 */
static BaseExpression*
boolean_term(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* b1;
    #undef	RETURN_TYPE_b1
    #define	RETURN_TYPE_b1 BaseExpression*

    BaseExpression* b2;
    #undef	RETURN_TYPE_b2
    #define	RETURN_TYPE_b2 BaseExpression*

    /* Initialize rule variables
     */

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:73:2: (b1= boolean_value ( AND b2= boolean_value )* )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:73:4: b1= boolean_value ( AND b2= boolean_value )*
        {
            FOLLOWPUSH(FOLLOW_boolean_value_in_boolean_term138);
            b1=boolean_value(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleboolean_termEx;
            }


            {

                	   val= 
                b1
                ;

                	
            }


            // /home/cross/workspace/djondb/db/grammars/filter_expression.g:77:3: ( AND b2= boolean_value )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case AND:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:77:4: AND b2= boolean_value
            	    {
            	         MATCHT(AND, &FOLLOW_AND_in_boolean_term146);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleboolean_termEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_boolean_value_in_boolean_term150);
            	        b2=boolean_value(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleboolean_termEx;
            	        }


            	        {

            	            	   BinaryExpression* be = new BinaryExpression(FO_AND);
            	            	   be->push(val
            	            );
            	            	   be->push(b2
            	            );
            	            	   val= be;

            	            	 
            	        }


            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleboolean_termEx; /* Prevent compiler warnings */
    ruleboolean_termEx: ;



    return val;
}
/* $ANTLR end boolean_term */

/**
 * $ANTLR start boolean_value
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:85:1: boolean_value returns [BaseExpression* val] : ( parenthesized_boolean | nonparentherized_boolean );
 */
static BaseExpression*
boolean_value(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* parenthesized_boolean3;
    #undef	RETURN_TYPE_parenthesized_boolean3
    #define	RETURN_TYPE_parenthesized_boolean3 BaseExpression*

    BaseExpression* nonparentherized_boolean4;
    #undef	RETURN_TYPE_nonparentherized_boolean4
    #define	RETURN_TYPE_nonparentherized_boolean4 BaseExpression*

    /* Initialize rule variables
     */

    {
        {
            //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:86:2: ( parenthesized_boolean | nonparentherized_boolean )

            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) )
            {
            case LPAREN:
            	{
            		alt3=1;
            	}
                break;
            case INT:
            case STRING:
            case XPATH:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleboolean_valueEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:86:4: parenthesized_boolean
        	    {
        	        FOLLOWPUSH(FOLLOW_parenthesized_boolean_in_boolean_value170);
        	        parenthesized_boolean3=parenthesized_boolean(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleboolean_valueEx;
        	        }


        	        {

        	            	   val= 
        	            parenthesized_boolean3
        	            ;

        	            	
        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:89:2: nonparentherized_boolean
        	    {
        	        FOLLOWPUSH(FOLLOW_nonparentherized_boolean_in_boolean_value177);
        	        nonparentherized_boolean4=nonparentherized_boolean(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleboolean_valueEx;
        	        }


        	        {

        	            	   val= 
        	            nonparentherized_boolean4
        	            ;

        	            	
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleboolean_valueEx; /* Prevent compiler warnings */
    ruleboolean_valueEx: ;



    return val;
}
/* $ANTLR end boolean_value */

/**
 * $ANTLR start parenthesized_boolean
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:93:1: parenthesized_boolean returns [BaseExpression* val] : LPAREN boolean_expr RPAREN ;
 */
static BaseExpression*
parenthesized_boolean(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* boolean_expr5;
    #undef	RETURN_TYPE_boolean_expr5
    #define	RETURN_TYPE_boolean_expr5 BaseExpression*

    /* Initialize rule variables
     */

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:94:2: ( LPAREN boolean_expr RPAREN )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:94:4: LPAREN boolean_expr RPAREN
        {
             MATCHT(LPAREN, &FOLLOW_LPAREN_in_parenthesized_boolean193);
            if  (HASEXCEPTION())
            {
                goto ruleparenthesized_booleanEx;
            }


            FOLLOWPUSH(FOLLOW_boolean_expr_in_parenthesized_boolean195);
            boolean_expr5=boolean_expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleparenthesized_booleanEx;
            }


            {

                	   val= 
                boolean_expr5
                ;

                	
            }


             MATCHT(RPAREN, &FOLLOW_RPAREN_in_parenthesized_boolean199);
            if  (HASEXCEPTION())
            {
                goto ruleparenthesized_booleanEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleparenthesized_booleanEx; /* Prevent compiler warnings */
    ruleparenthesized_booleanEx: ;



    return val;
}
/* $ANTLR end parenthesized_boolean */

/**
 * $ANTLR start nonparentherized_boolean
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:98:1: nonparentherized_boolean returns [BaseExpression* val] : u1= unary_expr ( OPER u2= unary_expr )* ;
 */
static BaseExpression*
nonparentherized_boolean(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    pANTLR3_COMMON_TOKEN    OPER6;
    BaseExpression* u1;
    #undef	RETURN_TYPE_u1
    #define	RETURN_TYPE_u1 BaseExpression*

    BaseExpression* u2;
    #undef	RETURN_TYPE_u2
    #define	RETURN_TYPE_u2 BaseExpression*

    /* Initialize rule variables
     */

    OPER6       = NULL;

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:99:2: (u1= unary_expr ( OPER u2= unary_expr )* )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:99:4: u1= unary_expr ( OPER u2= unary_expr )*
        {
            FOLLOWPUSH(FOLLOW_unary_expr_in_nonparentherized_boolean215);
            u1=unary_expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulenonparentherized_booleanEx;
            }


            {

                	   val= 
                u1
                ;

                	
            }


            // /home/cross/workspace/djondb/db/grammars/filter_expression.g:101:4: ( OPER u2= unary_expr )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case OPER:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:101:6: OPER u2= unary_expr
            	    {
            	        OPER6 = (pANTLR3_COMMON_TOKEN) MATCHT(OPER, &FOLLOW_OPER_in_nonparentherized_boolean221);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulenonparentherized_booleanEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_unary_expr_in_nonparentherized_boolean225);
            	        u2=unary_expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulenonparentherized_booleanEx;
            	        }


            	        {

            	            	   FILTER_OPERATORS oper = parseFilterOperator((char*)(OPER6->getText(OPER6))->chars);
            	            	   BinaryExpression* be = new BinaryExpression(oper);
            	            	   be->push(
            	            val
            	            );
            	            	   be->push(u2
            	            );
            	            	   val= be;

            	            	
            	        }


            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulenonparentherized_booleanEx; /* Prevent compiler warnings */
    rulenonparentherized_booleanEx: ;



    return val;
}
/* $ANTLR end nonparentherized_boolean */

/**
 * $ANTLR start unary_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:111:1: unary_expr returns [BaseExpression* val] : (c1= constant_expr |x1= xpath_expr ) ;
 */
static BaseExpression*
unary_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    BaseExpression* c1;
    #undef	RETURN_TYPE_c1
    #define	RETURN_TYPE_c1 BaseExpression*

    BaseExpression* x1;
    #undef	RETURN_TYPE_x1
    #define	RETURN_TYPE_x1 BaseExpression*

    /* Initialize rule variables
     */


    	     val = NULL;
    	
    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:115:2: ( (c1= constant_expr |x1= xpath_expr ) )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:115:4: (c1= constant_expr |x1= xpath_expr )
        {
            // /home/cross/workspace/djondb/db/grammars/filter_expression.g:115:4: (c1= constant_expr |x1= xpath_expr )
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case INT:
                case STRING:
                	{
                		alt5=1;
                	}
                    break;
                case XPATH:
                	{
                		alt5=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 5;
                    EXCEPTION->state        = 0;


                    goto ruleunary_exprEx;

                }

                switch (alt5)
                {
            	case 1:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:115:5: c1= constant_expr
            	    {
            	        FOLLOWPUSH(FOLLOW_constant_expr_in_unary_expr255);
            	        c1=constant_expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleunary_exprEx;
            	        }


            	        {

            	            	        val= c1;

            	            	
            	        }


            	    }
            	    break;
            	case 2:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:117:6: x1= xpath_expr
            	    {
            	        FOLLOWPUSH(FOLLOW_xpath_expr_in_unary_expr263);
            	        x1=xpath_expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleunary_exprEx;
            	        }


            	        {

            	            	        val= x1;

            	            	
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleunary_exprEx; /* Prevent compiler warnings */
    ruleunary_exprEx: ;



    return val;
}
/* $ANTLR end unary_expr */

/**
 * $ANTLR start xpath_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:121:1: xpath_expr returns [BaseExpression* val] : XPATH ;
 */
static BaseExpression*
xpath_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    pANTLR3_COMMON_TOKEN    XPATH7;

    /* Initialize rule variables
     */

    XPATH7       = NULL;

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:122:2: ( XPATH )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:122:4: XPATH
        {
            XPATH7 = (pANTLR3_COMMON_TOKEN) MATCHT(XPATH, &FOLLOW_XPATH_in_xpath_expr280);
            if  (HASEXCEPTION())
            {
                goto rulexpath_exprEx;
            }


            {

                	     char* text = (char*)(XPATH7->getText(XPATH7))->chars;
                	     SimpleExpression* result = new SimpleExpression(text);
                	     
                val= result;

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulexpath_exprEx; /* Prevent compiler warnings */
    rulexpath_exprEx: ;



    return val;
}
/* $ANTLR end xpath_expr */

/**
 * $ANTLR start constant_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:128:1: constant_expr returns [BaseExpression* val] : ( INT | STRING ) ;
 */
static BaseExpression*
constant_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    pANTLR3_COMMON_TOKEN    INT8;
    pANTLR3_COMMON_TOKEN    STRING9;

    /* Initialize rule variables
     */

    INT8       = NULL;
    STRING9       = NULL;

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:129:2: ( ( INT | STRING ) )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:129:4: ( INT | STRING )
        {
            // /home/cross/workspace/djondb/db/grammars/filter_expression.g:129:4: ( INT | STRING )
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case INT:
                	{
                		alt6=1;
                	}
                    break;
                case STRING:
                	{
                		alt6=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 6;
                    EXCEPTION->state        = 0;


                    goto ruleconstant_exprEx;

                }

                switch (alt6)
                {
            	case 1:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:129:5: INT
            	    {
            	        INT8 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_constant_expr296);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconstant_exprEx;
            	        }


            	        {

            	            	    int i = atoi((char*)(INT8->getText(INT8))->chars);
            	            	    
            	            val= new ConstantExpression(i);

            	            	
            	        }


            	    }
            	    break;
            	case 2:
            	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:133:6: STRING
            	    {
            	        STRING9 = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_constant_expr303);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleconstant_exprEx;
            	        }


            	        {

            	            	    char* ptext = (char*)(STRING9->getText(STRING9))->chars;
            	            	    char* text = (char*)malloc(strlen(ptext) - 1);
            	            	    memset(text, 0, strlen(ptext) - 1);
            	            	    memcpy(text, ptext + 1, strlen(ptext) - 2);
            	            	    
            	            	    
            	            val= new ConstantExpression(text);

            	            	    free (text);
            	            	
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconstant_exprEx; /* Prevent compiler warnings */
    ruleconstant_exprEx: ;



    return val;
}
/* $ANTLR end constant_expr */

/**
 * $ANTLR start operand_expr
 * /home/cross/workspace/djondb/db/grammars/filter_expression.g:143:1: operand_expr returns [BaseExpression* val] : OPER ;
 */
static BaseExpression*
operand_expr(pfilter_expressionParser ctx)
{
    BaseExpression* val;


    /* Initialize rule variables
     */

    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:144:2: ( OPER )
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:144:4: OPER
        {
             MATCHT(OPER, &FOLLOW_OPER_in_operand_expr318);
            if  (HASEXCEPTION())
            {
                goto ruleoperand_exprEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleoperand_exprEx; /* Prevent compiler warnings */
    ruleoperand_exprEx: ;



    return val;
}
/* $ANTLR end operand_expr */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
