/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/cross/workspace/djondb/db/grammars/filter_expression.g
 *     -                            On : 2012-07-19 16:56:18
 *     -                 for the lexer : filter_expressionLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "filter_expressionLexer.h"
/* ----------------------------------------- */


/** String literals used by filter_expressionLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x6E, 0x6F, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x61, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x5C, 0x22,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x5C, 0x27,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pfilter_expressionLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pfilter_expressionLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pfilter_expressionLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pfilter_expressionLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mNOT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mOPER    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mOPER_BINARY    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mFLOAT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMENT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mDOLLAR    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mXPATH    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mEXPONENT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mHEX_DIGIT    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mESC_SEQ    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mOCTAL_ESC    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mUNICODE_ESC    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMA    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mLPAREN    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mRPAREN    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mLBRAN    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mRBRAN    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mLBRAK    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mRBRAK    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mCOLON    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mSEMICOLON    (pfilter_expressionLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pfilter_expressionLexer ctx);
static void	filter_expressionLexerFree(pfilter_expressionLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
filter_expressionLexerFree  (pfilter_expressionLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
filter_expressionLexerReset (pfilter_expressionLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/cross/workspace/djondb/db/grammars/filter_expression.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called filter_expressionLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pfilter_expressionLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pfilter_expressionLexer filter_expressionLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return filter_expressionLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called filter_expressionLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pfilter_expressionLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pfilter_expressionLexer filter_expressionLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pfilter_expressionLexer ctx; // Context structure we will build and return

    ctx = (pfilter_expressionLexer) ANTLR3_CALLOC(1, sizeof(filter_expressionLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in filter_expressionLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our filter_expressionLexer interface
     */
    ctx->mNOT	= mNOT;
    ctx->mOPER	= mOPER;
    ctx->mOPER_BINARY	= mOPER_BINARY;
    ctx->mINT	= mINT;
    ctx->mFLOAT	= mFLOAT;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mWS	= mWS;
    ctx->mSTRING	= mSTRING;
    ctx->mDOLLAR	= mDOLLAR;
    ctx->mXPATH	= mXPATH;
    ctx->mEXPONENT	= mEXPONENT;
    ctx->mHEX_DIGIT	= mHEX_DIGIT;
    ctx->mESC_SEQ	= mESC_SEQ;
    ctx->mOCTAL_ESC	= mOCTAL_ESC;
    ctx->mUNICODE_ESC	= mUNICODE_ESC;
    ctx->mCOMMA	= mCOMMA;
    ctx->mLPAREN	= mLPAREN;
    ctx->mRPAREN	= mRPAREN;
    ctx->mLBRAN	= mLBRAN;
    ctx->mRBRAN	= mRBRAN;
    ctx->mLBRAK	= mLBRAK;
    ctx->mRBRAK	= mRBRAK;
    ctx->mCOLON	= mCOLON;
    ctx->mSEMICOLON	= mSEMICOLON;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= filter_expressionLexerFree;
    ctx->reset          = filter_expressionLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    157:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );
 */
static const ANTLR3_INT32 dfa10_eot[5] =
    {
	-1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa10_eof[5] =
    {
	-1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa10_min[5] =
    {
	46, 46, -1, -1, -1
    };
static const ANTLR3_INT32 dfa10_max[5] =
    {
	57, 101, -1, -1, -1
    };
static const ANTLR3_INT32 dfa10_accept[5] =
    {
	-1, -1, 2, 1, 3
    };
static const ANTLR3_INT32 dfa10_special[5] =
    {
	-1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa10_T_empty	    NULL

static const ANTLR3_INT32 dfa10_T0[] =
    {
	2, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };

static const ANTLR3_INT32 dfa10_T1[] =
    {
	3, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 4
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa10_transitions[] =
{
    dfa10_T0, dfa10_T1, NULL, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 10
 */
static
ANTLR3_CYCLIC_DFA cdfa10
    =	{
	    10,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"157:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa10_eot,	    /* EOT table			    */
	    dfa10_eof,	    /* EOF table			    */
	    dfa10_min,	    /* Minimum tokens for each state    */
	    dfa10_max,	    /* Maximum tokens for each state    */
	    dfa10_accept,	/* Accept table			    */
	    dfa10_special,	/* Special transition states	    */
	    dfa10_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 10
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( NOT | OPER | OPER_BINARY | INT | FLOAT | COMMENT | WS | STRING | DOLLAR | XPATH | COMMA | LPAREN | RPAREN | LBRAN | RBRAN | LBRAK | RBRAK | COLON | SEMICOLON );
 */
static const ANTLR3_INT32 dfa24_eot[22] =
    {
	-1, -1, -1, -1, 19, -1, -1, -1, -1, 20, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa24_eof[22] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa24_min[22] =
    {
	9, -1, -1, -1, 46, -1, -1, -1, -1, 34, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa24_max[22] =
    {
	125, -1, -1, -1, 101, -1, -1, -1, -1, 39, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa24_accept[22] =
    {
	-1, 1, 2, 3, -1, 5, 6, 7, 8, -1, 11, 12, 13, 14, 15, 16, 17, 18, 19, 4, 
	9, 10
    };
static const ANTLR3_INT32 dfa24_special[22] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa24_T_empty	    NULL

static const ANTLR3_INT32 dfa24_T0[] =
    {
	5, -1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5
    };

static const ANTLR3_INT32 dfa24_T1[] =
    {
	7, 7, -1, -1, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 7, -1, 8, -1, 9, -1, -1, 8, 11, 12, -1, -1, 10, -1, 5, 
	6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 17, 18, 2, 2, 2, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 15, -1, 16, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, 
	-1, 14
    };

static const ANTLR3_INT32 dfa24_T2[] =
    {
	21, -1, -1, -1, -1, 21
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa24_transitions[] =
{
    dfa24_T1, NULL, NULL, NULL, dfa24_T0, NULL, NULL, NULL, NULL, dfa24_T2, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 24
 */
static
ANTLR3_CYCLIC_DFA cdfa24
    =	{
	    24,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( NOT | OPER | OPER_BINARY | INT | FLOAT | COMMENT | WS | STRING | DOLLAR | XPATH | COMMA | LPAREN | RPAREN | LBRAN | RBRAN | LBRAK | RBRAK | COLON | SEMICOLON );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa24_eot,	    /* EOT table			    */
	    dfa24_eof,	    /* EOF table			    */
	    dfa24_min,	    /* Minimum tokens for each state    */
	    dfa24_max,	    /* Maximum tokens for each state    */
	    dfa24_accept,	/* Accept table			    */
	    dfa24_special,	/* Special transition states	    */
	    dfa24_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 24
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 149:5: ( 'not' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT
 *
 * Looks to match the characters the constitute the token NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:149:5: ( 'not' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:149:7: 'not'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleNOTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOTEx; /* Prevent compiler warnings */
    ruleNOTEx: ;

}
// $ANTLR end NOT

//   Comes from: 151:6: ( ( '==' | '>' | '>=' | '<' | '<=' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPER
 *
 * Looks to match the characters the constitute the token OPER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPER(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPER;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:6: ( ( '==' | '>' | '>=' | '<' | '<=' ) )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:8: ( '==' | '>' | '>=' | '<' | '<=' )
    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:8: ( '==' | '>' | '>=' | '<' | '<=' )
        {
            int alt1=5;
            switch ( LA(1) )
            {
            case '=':
            	{
            		alt1=1;
            	}
                break;
            case '>':
            	{
            		switch ( LA(2) )
            		{
            		case '=':
            			{
            				alt1=3;
            			}
            		    break;

            		default:
            		    alt1=2;
            		}

            	}
                break;
            case '<':
            	{
            		switch ( LA(2) )
            		{
            		case '=':
            			{
            				alt1=5;
            			}
            		    break;

            		default:
            		    alt1=4;
            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto ruleOPEREx;

            }

            switch (alt1)
            {
        	case 1:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:9: '=='
        	    {
        	        MATCHS(lit_2);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleOPEREx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:16: '>'
        	    {
        	        MATCHC('>');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleOPEREx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:22: '>='
        	    {
        	        MATCHS(lit_3);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleOPEREx;
        	        }




        	    }
        	    break;
        	case 4:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:29: '<'
        	    {
        	        MATCHC('<');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleOPEREx;
        	        }


        	    }
        	    break;
        	case 5:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:151:35: '<='
        	    {
        	        MATCHS(lit_4);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleOPEREx;
        	        }




        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPEREx; /* Prevent compiler warnings */
    ruleOPEREx: ;

}
// $ANTLR end OPER

//   Comes from: 153:2: ( 'and' | 'or' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPER_BINARY
 *
 * Looks to match the characters the constitute the token OPER_BINARY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPER_BINARY(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPER_BINARY;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:153:2: ( 'and' | 'or' )

        ANTLR3_UINT32 alt2;

        alt2=2;

        switch ( LA(1) )
        {
        case 'a':
        	{
        		alt2=1;
        	}
            break;
        case 'o':
        	{
        		alt2=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 2;
            EXCEPTION->state        = 0;


            goto ruleOPER_BINARYEx;

        }

        switch (alt2)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:153:4: 'and'
    	    {
    	        MATCHS(lit_5);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOPER_BINARYEx;
    	        }




    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:153:12: 'or'
    	    {
    	        MATCHS(lit_6);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOPER_BINARYEx;
    	        }




    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPER_BINARYEx; /* Prevent compiler warnings */
    ruleOPER_BINARYEx: ;

}
// $ANTLR end OPER_BINARY

//   Comes from: 155:5: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:155:5: ( ( '0' .. '9' )+ )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:155:7: ( '0' .. '9' )+
    {
        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:155:7: ( '0' .. '9' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 158:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FLOAT
 *
 * Looks to match the characters the constitute the token FLOAT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFLOAT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FLOAT;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )

        ANTLR3_UINT32 alt10;

        alt10=3;

        alt10 = cdfa10.predict(ctx, RECOGNIZER, ISTREAM, &cdfa10);
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }

        switch (alt10)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
    	    {
    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:9: ( '0' .. '9' )+
    	        {
    	            int cnt4=0;

    	            for (;;)
    	            {
    	                int alt4=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt4=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt4)
    	        	{
    	        	    case 1:
    	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleFLOATEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt4 >= 1 )
    	        		{
    	        		    goto loop4;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleFLOATEx;
    	        	}
    	        	cnt4++;
    	            }
    	            loop4: ;	/* Jump to here if this rule does not match */
    	        }

    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleFLOATEx;
    	        }


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:25: ( '0' .. '9' )*

    	        for (;;)
    	        {
    	            int alt5=2;
    	            switch ( LA(1) )
    	            {
    	            case '0':
    	            case '1':
    	            case '2':
    	            case '3':
    	            case '4':
    	            case '5':
    	            case '6':
    	            case '7':
    	            case '8':
    	            case '9':
    	            	{
    	            		alt5=1;
    	            	}
    	                break;

    	            }

    	            switch (alt5)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    	        	    {
    	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleFLOATEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop5;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop5: ; /* Jump out to here if this rule does not match */


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:37: ( EXPONENT )?
    	        {
    	            int alt6=2;
    	            switch ( LA(1) )
    	            {
    	                case 'E':
    	                case 'e':
    	                	{
    	                		alt6=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt6)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:158:37: EXPONENT
    	        	    {
    	        	        /* 158:37: EXPONENT */
    	        	        mEXPONENT(ctx );
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleFLOATEx;
    	        	        }



    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:159:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
    	    {
    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleFLOATEx;
    	        }


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:159:13: ( '0' .. '9' )+
    	        {
    	            int cnt7=0;

    	            for (;;)
    	            {
    	                int alt7=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt7=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt7)
    	        	{
    	        	    case 1:
    	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleFLOATEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt7 >= 1 )
    	        		{
    	        		    goto loop7;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleFLOATEx;
    	        	}
    	        	cnt7++;
    	            }
    	            loop7: ;	/* Jump to here if this rule does not match */
    	        }

    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:159:25: ( EXPONENT )?
    	        {
    	            int alt8=2;
    	            switch ( LA(1) )
    	            {
    	                case 'E':
    	                case 'e':
    	                	{
    	                		alt8=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt8)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:159:25: EXPONENT
    	        	    {
    	        	        /* 159:25: EXPONENT */
    	        	        mEXPONENT(ctx );
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleFLOATEx;
    	        	        }



    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;
    	case 3:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:160:9: ( '0' .. '9' )+ EXPONENT
    	    {
    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:160:9: ( '0' .. '9' )+
    	        {
    	            int cnt9=0;

    	            for (;;)
    	            {
    	                int alt9=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt9=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt9)
    	        	{
    	        	    case 1:
    	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleFLOATEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt9 >= 1 )
    	        		{
    	        		    goto loop9;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleFLOATEx;
    	        	}
    	        	cnt9++;
    	            }
    	            loop9: ;	/* Jump to here if this rule does not match */
    	        }

    	        /* 160:9: ( '0' .. '9' )+ EXPONENT */
    	        mEXPONENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleFLOATEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFLOATEx; /* Prevent compiler warnings */
    ruleFLOATEx: ;

}
// $ANTLR end FLOAT

//   Comes from: 164:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMENT;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:164:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )

        ANTLR3_UINT32 alt14;

        alt14=2;

        switch ( LA(1) )
        {
        case '/':
        	{
        		switch ( LA(2) )
        		{
        		case '/':
        			{
        				alt14=1;
        			}
        		    break;
        		case '*':
        			{
        				alt14=2;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 14;
        		    EXCEPTION->state        = 1;


        		    goto ruleCOMMENTEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 14;
            EXCEPTION->state        = 0;


            goto ruleCOMMENTEx;

        }

        switch (alt14)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:164:9: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
    	    {
    	        MATCHS(lit_7);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:164:14: (~ ( '\\n' | '\\r' ) )*

    	        for (;;)
    	        {
    	            int alt11=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA11_0 = LA(1);
    	                if ( (((LA11_0 >= 0x0000) && (LA11_0 <= '\t')) || ((LA11_0 >= 0x000B) && (LA11_0 <= '\f')) || ((LA11_0 >= 0x000E) && (LA11_0 <= 0xFFFF))))
    	                {
    	                    alt11=1;
    	                }

    	            }
    	            switch (alt11)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    	        	    {
    	        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop11;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop11: ; /* Jump out to here if this rule does not match */


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:164:28: ( '\\r' )?
    	        {
    	            int alt12=2;
    	            switch ( LA(1) )
    	            {
    	                case '\r':
    	                	{
    	                		alt12=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt12)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:164:28: '\\r'
    	        	    {
    	        	        MATCHC('\r');
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	            }
    	        }

    	        MATCHC('\n');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }


    	        {
    	            LEXSTATE->channel=HIDDEN;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:165:9: '/*' ( options {greedy=false; } : . )* '*/'
    	    {
    	        MATCHS(lit_8);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:165:14: ( options {greedy=false; } : . )*

    	        for (;;)
    	        {
    	            int alt13=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA13_0 = LA(1);
    	                if ( (LA13_0 == '*'))
    	                {
    	                    {
    	                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                        */
    	                        int LA13_1 = LA(2);
    	                        if ( (LA13_1 == '/'))
    	                        {
    	                            alt13=2;
    	                        }
    	                        else if ( (((LA13_1 >= 0x0000) && (LA13_1 <= '.')) || ((LA13_1 >= '0') && (LA13_1 <= 0xFFFF))))
    	                        {
    	                            alt13=1;
    	                        }

    	                    }
    	                }
    	                else if ( (((LA13_0 >= 0x0000) && (LA13_0 <= ')')) || ((LA13_0 >= '+') && (LA13_0 <= 0xFFFF))))
    	                {
    	                    alt13=1;
    	                }

    	            }
    	            switch (alt13)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:165:42: .
    	        	    {
    	        	        MATCHANY();
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleCOMMENTEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop13;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop13: ; /* Jump out to here if this rule does not match */


    	        MATCHS(lit_9);
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleCOMMENTEx;
    	        }




    	        {
    	            LEXSTATE->channel=HIDDEN;
    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 168:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:168:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:168:9: ( ' ' | '\\t' | '\\r' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleWSEx;
        }


        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

//   Comes from: 175:10: ( '\\\"' ( options {greedy=false; } : (~ ( '\\\"' ) | ( '\\\\\"' ) ) )* '\\\"' | '\\'' ( options {greedy=false; } : (~ ( '\\'' ) | ( '\\\\\\'' ) ) )* '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:10: ( '\\\"' ( options {greedy=false; } : (~ ( '\\\"' ) | ( '\\\\\"' ) ) )* '\\\"' | '\\'' ( options {greedy=false; } : (~ ( '\\'' ) | ( '\\\\\\'' ) ) )* '\\'' )

        ANTLR3_UINT32 alt19;

        alt19=2;

        switch ( LA(1) )
        {
        case '"':
        	{
        		alt19=1;
        	}
            break;
        case '\'':
        	{
        		alt19=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 19;
            EXCEPTION->state        = 0;


            goto ruleSTRINGEx;

        }

        switch (alt19)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:13: '\\\"' ( options {greedy=false; } : (~ ( '\\\"' ) | ( '\\\\\"' ) ) )* '\\\"'
    	    {
    	        MATCHC('\"');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRINGEx;
    	        }


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:18: ( options {greedy=false; } : (~ ( '\\\"' ) | ( '\\\\\"' ) ) )*

    	        for (;;)
    	        {
    	            int alt16=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA16_0 = LA(1);
    	                if ( (((LA16_0 >= 0x0000) && (LA16_0 <= '!')) || ((LA16_0 >= '#') && (LA16_0 <= 0xFFFF))))
    	                {
    	                    alt16=1;
    	                }
    	                else if ( (LA16_0 == '"'))
    	                {
    	                    alt16=2;
    	                }

    	            }
    	            switch (alt16)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:46: (~ ( '\\\"' ) | ( '\\\\\"' ) )
    	        	    {
    	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:46: (~ ( '\\\"' ) | ( '\\\\\"' ) )
    	        	        {
    	        	            int alt15=2;
    	        	            {
    	        	                int LA15_0 = LA(1);
    	        	                if ( (LA15_0 == '\\'))
    	        	                {
    	        	                    {
    	        	                        int LA15_1 = LA(2);
    	        	                        if ( (LA15_1 == '"'))
    	        	                        {
    	        	                            {
    	        	                                int LA15_3 = LA(3);
    	        	                                if ( (((LA15_3 >= 0x0000) && (LA15_3 <= 0xFFFF))))
    	        	                                {
    	        	                                    alt15=2;
    	        	                                }
    	        	                                else
    	        	                                {
    	        	                                    alt15=1;
    	        	                                }
    	        	                            }
    	        	                        }
    	        	                        else if ( (((LA15_1 >= 0x0000) && (LA15_1 <= '!')) || ((LA15_1 >= '#') && (LA15_1 <= 0xFFFF))))
    	        	                        {
    	        	                            alt15=1;
    	        	                        }
    	        	                        else
    	        	                        {

    	        	                            CONSTRUCTEX();
    	        	                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
    	        	                            EXCEPTION->message      = (void *)"";
    	        	                            EXCEPTION->decisionNum  = 15;
    	        	                            EXCEPTION->state        = 1;


    	        	                            goto ruleSTRINGEx;

    	        	                        }
    	        	                    }
    	        	                }
    	        	                else if ( (((LA15_0 >= 0x0000) && (LA15_0 <= '!')) || ((LA15_0 >= '#') && (LA15_0 <= '[')) || ((LA15_0 >= ']') && (LA15_0 <= 0xFFFF))))
    	        	                {
    	        	                    alt15=1;
    	        	                }
    	        	                else
    	        	                {

    	        	                    CONSTRUCTEX();
    	        	                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
    	        	                    EXCEPTION->message      = (void *)"";
    	        	                    EXCEPTION->decisionNum  = 15;
    	        	                    EXCEPTION->state        = 0;


    	        	                    goto ruleSTRINGEx;

    	        	                }
    	        	            }
    	        	            switch (alt15)
    	        	            {
    	        	        	case 1:
    	        	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:47: ~ ( '\\\"' )
    	        	        	    {
    	        	        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
    	        	        	        {
    	        	        	            CONSUME();
    	        	        	        }
    	        	        	        else
    	        	        	        {
    	        	        	            CONSTRUCTEX();
    	        	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	        	            LRECOVER();
    	        	        	            goto ruleSTRINGEx;
    	        	        	        }


    	        	        	    }
    	        	        	    break;
    	        	        	case 2:
    	        	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:57: ( '\\\\\"' )
    	        	        	    {
    	        	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:57: ( '\\\\\"' )
    	        	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:58: '\\\\\"'
    	        	        	        {
    	        	        	            MATCHS(lit_10);
    	        	        	            if  (HASEXCEPTION())
    	        	        	            {
    	        	        	                goto ruleSTRINGEx;
    	        	        	            }




    	        	        	        }


    	        	        	    }
    	        	        	    break;

    	        	            }
    	        	        }

    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop16;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop16: ; /* Jump out to here if this rule does not match */


    	        MATCHC('\"');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRINGEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:76: '\\'' ( options {greedy=false; } : (~ ( '\\'' ) | ( '\\\\\\'' ) ) )* '\\''
    	    {
    	        MATCHC('\'');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRINGEx;
    	        }


    	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:81: ( options {greedy=false; } : (~ ( '\\'' ) | ( '\\\\\\'' ) ) )*

    	        for (;;)
    	        {
    	            int alt18=2;
    	            {
    	               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                */
    	                int LA18_0 = LA(1);
    	                if ( (((LA18_0 >= 0x0000) && (LA18_0 <= '&')) || ((LA18_0 >= '(') && (LA18_0 <= 0xFFFF))))
    	                {
    	                    alt18=1;
    	                }
    	                else if ( (LA18_0 == '\''))
    	                {
    	                    alt18=2;
    	                }

    	            }
    	            switch (alt18)
    	            {
    	        	case 1:
    	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:109: (~ ( '\\'' ) | ( '\\\\\\'' ) )
    	        	    {
    	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:109: (~ ( '\\'' ) | ( '\\\\\\'' ) )
    	        	        {
    	        	            int alt17=2;
    	        	            {
    	        	                int LA17_0 = LA(1);
    	        	                if ( (LA17_0 == '\\'))
    	        	                {
    	        	                    {
    	        	                        int LA17_1 = LA(2);
    	        	                        if ( (LA17_1 == '\''))
    	        	                        {
    	        	                            {
    	        	                                int LA17_3 = LA(3);
    	        	                                if ( (((LA17_3 >= 0x0000) && (LA17_3 <= 0xFFFF))))
    	        	                                {
    	        	                                    alt17=2;
    	        	                                }
    	        	                                else
    	        	                                {
    	        	                                    alt17=1;
    	        	                                }
    	        	                            }
    	        	                        }
    	        	                        else if ( (((LA17_1 >= 0x0000) && (LA17_1 <= '&')) || ((LA17_1 >= '(') && (LA17_1 <= 0xFFFF))))
    	        	                        {
    	        	                            alt17=1;
    	        	                        }
    	        	                        else
    	        	                        {

    	        	                            CONSTRUCTEX();
    	        	                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
    	        	                            EXCEPTION->message      = (void *)"";
    	        	                            EXCEPTION->decisionNum  = 17;
    	        	                            EXCEPTION->state        = 1;


    	        	                            goto ruleSTRINGEx;

    	        	                        }
    	        	                    }
    	        	                }
    	        	                else if ( (((LA17_0 >= 0x0000) && (LA17_0 <= '&')) || ((LA17_0 >= '(') && (LA17_0 <= '[')) || ((LA17_0 >= ']') && (LA17_0 <= 0xFFFF))))
    	        	                {
    	        	                    alt17=1;
    	        	                }
    	        	                else
    	        	                {

    	        	                    CONSTRUCTEX();
    	        	                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
    	        	                    EXCEPTION->message      = (void *)"";
    	        	                    EXCEPTION->decisionNum  = 17;
    	        	                    EXCEPTION->state        = 0;


    	        	                    goto ruleSTRINGEx;

    	        	                }
    	        	            }
    	        	            switch (alt17)
    	        	            {
    	        	        	case 1:
    	        	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:110: ~ ( '\\'' )
    	        	        	    {
    	        	        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= 0xFFFF)) )
    	        	        	        {
    	        	        	            CONSUME();
    	        	        	        }
    	        	        	        else
    	        	        	        {
    	        	        	            CONSTRUCTEX();
    	        	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	        	            LRECOVER();
    	        	        	            goto ruleSTRINGEx;
    	        	        	        }


    	        	        	    }
    	        	        	    break;
    	        	        	case 2:
    	        	        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:120: ( '\\\\\\'' )
    	        	        	    {
    	        	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:120: ( '\\\\\\'' )
    	        	        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:175:121: '\\\\\\''
    	        	        	        {
    	        	        	            MATCHS(lit_11);
    	        	        	            if  (HASEXCEPTION())
    	        	        	            {
    	        	        	                goto ruleSTRINGEx;
    	        	        	            }




    	        	        	        }


    	        	        	    }
    	        	        	    break;

    	        	            }
    	        	        }

    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop18;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop18: ; /* Jump out to here if this rule does not match */


    	        MATCHC('\'');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleSTRINGEx;
    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 177:9: ( '$' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOLLAR
 *
 * Looks to match the characters the constitute the token DOLLAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOLLAR(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DOLLAR;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:177:9: ( '$' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:177:12: '$'
    {
        MATCHC('$');
        if  (HASEXCEPTION())
        {
            goto ruleDOLLAREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDOLLAREx; /* Prevent compiler warnings */
    ruleDOLLAREx: ;

}
// $ANTLR end DOLLAR

//   Comes from: 179:5: ( DOLLAR STRING )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start XPATH
 *
 * Looks to match the characters the constitute the token XPATH
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mXPATH(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = XPATH;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:179:5: ( DOLLAR STRING )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:179:7: DOLLAR STRING
    {
        /* 179:7: DOLLAR STRING */
        mDOLLAR(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleXPATHEx;
        }



        /* 179:7: DOLLAR STRING */
        mSTRING(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleXPATHEx;
        }



    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleXPATHEx; /* Prevent compiler warnings */
    ruleXPATHEx: ;

}
// $ANTLR end XPATH

//   Comes from: 184:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EXPONENT
 *
 * Looks to match the characters the constitute the token EXPONENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEXPONENT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:184:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:184:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
    {
        if ( LA(1) == 'E' || LA(1) == 'e' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleEXPONENTEx;
        }


        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:184:22: ( '+' | '-' )?
        {
            int alt20=2;
            switch ( LA(1) )
            {
                case '+':
                case '-':
                	{
                		alt20=1;
                	}
                    break;
            }

            switch (alt20)
            {
        	case 1:
        	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
        	    {
        	        if ( LA(1) == '+' || LA(1) == '-' )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleEXPONENTEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:184:33: ( '0' .. '9' )+
        {
            int cnt21=0;

            for (;;)
            {
                int alt21=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt21=1;
        		}
        	    break;

        	}

        	switch (alt21)
        	{
        	    case 1:
        	        // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleEXPONENTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt21 >= 1 )
        		{
        		    goto loop21;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleEXPONENTEx;
        	}
        	cnt21++;
            }
            loop21: ;	/* Jump to here if this rule does not match */
        }

    }


    // This is where rules clean up and exit
    //
    goto ruleEXPONENTEx; /* Prevent compiler warnings */
    ruleEXPONENTEx: ;

}
// $ANTLR end EXPONENT

//   Comes from: 187:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HEX_DIGIT
 *
 * Looks to match the characters the constitute the token HEX_DIGIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHEX_DIGIT(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:187:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:
    {
        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleHEX_DIGITEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleHEX_DIGITEx; /* Prevent compiler warnings */
    ruleHEX_DIGITEx: ;

}
// $ANTLR end HEX_DIGIT

//   Comes from: 191:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | UNICODE_ESC | OCTAL_ESC )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ESC_SEQ
 *
 * Looks to match the characters the constitute the token ESC_SEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mESC_SEQ(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:191:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | UNICODE_ESC | OCTAL_ESC )

        ANTLR3_UINT32 alt22;

        alt22=3;

        switch ( LA(1) )
        {
        case '\\':
        	{
        		switch ( LA(2) )
        		{
        		case '"':
        		case '\'':
        		case '\\':
        		case 'b':
        		case 'f':
        		case 'n':
        		case 'r':
        		case 't':
        			{
        				alt22=1;
        			}
        		    break;
        		case 'u':
        			{
        				alt22=2;
        			}
        		    break;
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        			{
        				alt22=3;
        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 22;
        		    EXCEPTION->state        = 1;


        		    goto ruleESC_SEQEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 22;
            EXCEPTION->state        = 0;


            goto ruleESC_SEQEx;

        }

        switch (alt22)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:191:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleESC_SEQEx;
    	        }


    	        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleESC_SEQEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:192:9: UNICODE_ESC
    	    {
    	        /* 192:9: UNICODE_ESC */
    	        mUNICODE_ESC(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleESC_SEQEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:193:13: OCTAL_ESC
    	    {
    	        /* 193:13: OCTAL_ESC */
    	        mOCTAL_ESC(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleESC_SEQEx;
    	        }



    	    }
    	    break;

        }
    }

    // This is where rules clean up and exit
    //
    goto ruleESC_SEQEx; /* Prevent compiler warnings */
    ruleESC_SEQEx: ;

}
// $ANTLR end ESC_SEQ

//   Comes from: 198:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OCTAL_ESC
 *
 * Looks to match the characters the constitute the token OCTAL_ESC
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOCTAL_ESC(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;


    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:198:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )

        ANTLR3_UINT32 alt23;

        alt23=3;

        switch ( LA(1) )
        {
        case '\\':
        	{
        		switch ( LA(2) )
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        							{
        								alt23=1;
        							}
        						    break;

        						default:
        						    alt23=2;
        						}

        					}
        				    break;

        				default:
        				    alt23=3;
        				}

        			}
        		    break;
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        					{
        						alt23=2;
        					}
        				    break;

        				default:
        				    alt23=3;
        				}

        			}
        		    break;

        		default:
        		    CONSTRUCTEX();
        		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        		    EXCEPTION->message      = (void *)"";
        		    EXCEPTION->decisionNum  = 23;
        		    EXCEPTION->state        = 1;


        		    goto ruleOCTAL_ESCEx;

        		}

        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 23;
            EXCEPTION->state        = 0;


            goto ruleOCTAL_ESCEx;

        }

        switch (alt23)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:198:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '3')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:199:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:200:9: '\\\\' ( '0' .. '7' )
    	    {
    	        MATCHC('\\');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleOCTAL_ESCEx;
    	        }


    	        if ( ((LA(1) >= '0') && (LA(1) <= '7')) )
    	        {
    	            CONSUME();
    	        }
    	        else
    	        {
    	            CONSTRUCTEX();
    	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	            LRECOVER();
    	            goto ruleOCTAL_ESCEx;
    	        }


    	    }
    	    break;

        }
    }

    // This is where rules clean up and exit
    //
    goto ruleOCTAL_ESCEx; /* Prevent compiler warnings */
    ruleOCTAL_ESCEx: ;

}
// $ANTLR end OCTAL_ESC

//   Comes from: 205:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start UNICODE_ESC
 *
 * Looks to match the characters the constitute the token UNICODE_ESC
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mUNICODE_ESC(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:205:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
    {
        MATCHC('\\');
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }


        MATCHC('u');
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }


        /* 205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT */
        mHEX_DIGIT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }



        /* 205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT */
        mHEX_DIGIT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }



        /* 205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT */
        mHEX_DIGIT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }



        /* 205:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT */
        mHEX_DIGIT(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleUNICODE_ESCEx;
        }



    }


    // This is where rules clean up and exit
    //
    goto ruleUNICODE_ESCEx; /* Prevent compiler warnings */
    ruleUNICODE_ESCEx: ;

}
// $ANTLR end UNICODE_ESC

//   Comes from: 208:2: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMA;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:208:2: ( ',' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:208:4: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 209:8: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAREN
 *
 * Looks to match the characters the constitute the token LPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAREN(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LPAREN;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:209:8: ( '(' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:209:10: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleLPARENEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLPARENEx; /* Prevent compiler warnings */
    ruleLPARENEx: ;

}
// $ANTLR end LPAREN

//   Comes from: 210:8: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAREN
 *
 * Looks to match the characters the constitute the token RPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAREN(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RPAREN;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:210:8: ( ')' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:210:10: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleRPARENEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRPARENEx; /* Prevent compiler warnings */
    ruleRPARENEx: ;

}
// $ANTLR end RPAREN

//   Comes from: 211:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LBRAN
 *
 * Looks to match the characters the constitute the token LBRAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLBRAN(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LBRAN;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:211:7: ( '{' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:211:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleLBRANEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLBRANEx; /* Prevent compiler warnings */
    ruleLBRANEx: ;

}
// $ANTLR end LBRAN

//   Comes from: 212:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RBRAN
 *
 * Looks to match the characters the constitute the token RBRAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRBRAN(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RBRAN;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:212:7: ( '}' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:212:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleRBRANEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRBRANEx; /* Prevent compiler warnings */
    ruleRBRANEx: ;

}
// $ANTLR end RBRAN

//   Comes from: 214:2: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LBRAK
 *
 * Looks to match the characters the constitute the token LBRAK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLBRAK(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LBRAK;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:214:2: ( '[' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:214:4: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleLBRAKEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLBRAKEx; /* Prevent compiler warnings */
    ruleLBRAKEx: ;

}
// $ANTLR end LBRAK

//   Comes from: 216:2: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RBRAK
 *
 * Looks to match the characters the constitute the token RBRAK
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRBRAK(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RBRAK;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:216:2: ( ']' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:216:4: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleRBRAKEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRBRAKEx; /* Prevent compiler warnings */
    ruleRBRAKEx: ;

}
// $ANTLR end RBRAK

//   Comes from: 218:2: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COLON;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:218:2: ( ':' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:218:4: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 220:9: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SEMICOLON
 *
 * Looks to match the characters the constitute the token SEMICOLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSEMICOLON(pfilter_expressionLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SEMICOLON;


    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:220:9: ( ';' )
    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:220:17: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleSEMICOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSEMICOLONEx; /* Prevent compiler warnings */
    ruleSEMICOLONEx: ;

}
// $ANTLR end SEMICOLON

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pfilter_expressionLexer ctx)
{
    {
        //  /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:8: ( NOT | OPER | OPER_BINARY | INT | FLOAT | COMMENT | WS | STRING | DOLLAR | XPATH | COMMA | LPAREN | RPAREN | LBRAN | RBRAN | LBRAK | RBRAK | COLON | SEMICOLON )

        ANTLR3_UINT32 alt24;

        alt24=19;

        alt24 = cdfa24.predict(ctx, RECOGNIZER, ISTREAM, &cdfa24);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt24)
        {
    	case 1:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:10: NOT
    	    {
    	        /* 1:10: NOT */
    	        mNOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:14: OPER
    	    {
    	        /* 1:14: OPER */
    	        mOPER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:19: OPER_BINARY
    	    {
    	        /* 1:19: OPER_BINARY */
    	        mOPER_BINARY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:31: INT
    	    {
    	        /* 1:31: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:35: FLOAT
    	    {
    	        /* 1:35: FLOAT */
    	        mFLOAT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:41: COMMENT
    	    {
    	        /* 1:41: COMMENT */
    	        mCOMMENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:49: WS
    	    {
    	        /* 1:49: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:52: STRING
    	    {
    	        /* 1:52: STRING */
    	        mSTRING(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:59: DOLLAR
    	    {
    	        /* 1:59: DOLLAR */
    	        mDOLLAR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:66: XPATH
    	    {
    	        /* 1:66: XPATH */
    	        mXPATH(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:72: COMMA
    	    {
    	        /* 1:72: COMMA */
    	        mCOMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:78: LPAREN
    	    {
    	        /* 1:78: LPAREN */
    	        mLPAREN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:85: RPAREN
    	    {
    	        /* 1:85: RPAREN */
    	        mRPAREN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:92: LBRAN
    	    {
    	        /* 1:92: LBRAN */
    	        mLBRAN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:98: RBRAN
    	    {
    	        /* 1:98: RBRAN */
    	        mRBRAN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:104: LBRAK
    	    {
    	        /* 1:104: LBRAK */
    	        mLBRAK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:110: RBRAK
    	    {
    	        /* 1:110: RBRAK */
    	        mRBRAK(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:116: COLON
    	    {
    	        /* 1:116: COLON */
    	        mCOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/cross/workspace/djondb/db/grammars/filter_expression.g:1:122: SEMICOLON
    	    {
    	        /* 1:122: SEMICOLON */
    	        mSEMICOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
