/*
 * MainScreen.java
 *
 * Created on September 2, 2008, 1:13 PM
 */
package com.sinco.client;

import com.sinco.client.model.MetadataModel;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.net.UnknownHostException;

/**
 *
 * @author  cross
 */
public class MainScreen extends javax.swing.JFrame {

    private Server currentServer;
    private MetadataModel metadataModel;

    /** Creates new form MainScreen */
    public MainScreen() {
        initComponents();
        setSize(1000, 1000);
        currentServer = new Server();
        currentServer.setHostAddress("localhost");
        currentServer.setHostPort(1048);
        currentServer.setLogged(true);
        currentServer.setPrivateKey("RTYUIO");
        currentServer.setSessionId("DFGHJKL");
        currentServer.setUserName("Cross");
        metadataModel = new MetadataModel(currentServer);
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                retrieveForms();
            }
        });
    }

    /**
     * Loads the login screen.
     */
    private void executeLoginScreen() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private void retrieveForms() {
        try {
            metadataModel.loadFormDefinitions();
        } catch (UnknownHostException ex) {
            executeLoginScreen();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        pnlDesk = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.setPreferredSize(new java.awt.Dimension(200, 64));
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        pnlDesk.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(pnlDesk);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem2.setText("New Process Instance");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Admin");

        jMenuItem1.setText("Process Definition Deployment");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    DeploymentForm form = new DeploymentForm();
    form.setVisible(true);
//jDesktopPane1.add(form);

}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    while (pnlDesk.getComponents().length > 0) {
        pnlDesk.remove(0);
    }
    ProcessWizardPanel panel = new ProcessWizardPanel(currentServer);
    panel.setVisible(true);
    pnlDesk.add(panel, BorderLayout.CENTER);
    pnlDesk.updateUI();
}//GEN-LAST:event_jMenuItem2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel pnlDesk;
    // End of variables declaration//GEN-END:variables
}
