/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace djondb {

using System;
using System.Runtime.InteropServices;

public class DjondbConnectionManager : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DjondbConnectionManager(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DjondbConnectionManager obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DjondbConnectionManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          djonwrapperPINVOKE.delete_DjondbConnectionManager(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DjondbConnectionManager() : this(djonwrapperPINVOKE.new_DjondbConnectionManager(), true) {
  }

  public static DjondbConnection getConnection(string host) {
    IntPtr cPtr = djonwrapperPINVOKE.DjondbConnectionManager_getConnection__SWIG_0(host);
    DjondbConnection ret = (cPtr == IntPtr.Zero) ? null : new DjondbConnection(cPtr, false);
    if (djonwrapperPINVOKE.SWIGPendingException.Pending) throw djonwrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DjondbConnection getConnection(string host, int port) {
    IntPtr cPtr = djonwrapperPINVOKE.DjondbConnectionManager_getConnection__SWIG_1(host, port);
    DjondbConnection ret = (cPtr == IntPtr.Zero) ? null : new DjondbConnection(cPtr, false);
    if (djonwrapperPINVOKE.SWIGPendingException.Pending) throw djonwrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void releaseConnection(DjondbConnection conn) {
    djonwrapperPINVOKE.DjondbConnectionManager_releaseConnection(DjondbConnection.getCPtr(conn));
  }

}

}
