/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace djondb {

using System;
using System.Runtime.InteropServices;

public class djonwrapper {
  public static FILTER_OPERATORS parseFilterOperator(string text) {
    FILTER_OPERATORS ret = (FILTER_OPERATORS)djonwrapperPINVOKE.parseFilterOperator(text);
    return ret;
  }

  public static SWIGTYPE_p_std__setT_std__string_t bson_splitSelect(string select) {
    SWIGTYPE_p_std__setT_std__string_t ret = new SWIGTYPE_p_std__setT_std__string_t(djonwrapperPINVOKE.bson_splitSelect(select), true);
    return ret;
  }

  public static string bson_subselect(string select, string elment) {
    string ret = djonwrapperPINVOKE.bson_subselect(select, elment);
    return ret;
  }

  public static readonly int SERVER_PORT = djonwrapperPINVOKE.SERVER_PORT_get();
}

}
