#ifndef ENGINE_DEFS_H_INCLUDED
#define ENGINE_DEFS_H_INCLUDED

enum InstanceStatus
{
    RUNNING,
    CLOSED,
    CANCELLED
};

enum TokenStatus {
    TOKENSTATUS_NONE,
    TOKENSTATUS_STARTED,
    TOKENSTATUS_USER,
    TOKENSTATUS_POSTUSER,
    TOKENSTATUS_ENDED
};

#endif // ENGINE_DEFS_H_INCLUDED
