#ifndef DBJAGUAR_GLOBAL_H
#define DBJAGUAR_GLOBAL_H

#include <QtCore/qglobal.h>

// class DBJAGUARSHARED_EXPORT test
#if defined(DBJAGUAR_LIBRARY)
#  define DBJAGUARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DBJAGUARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DBJAGUAR_GLOBAL_H
