#ifndef WORKFLOW_GLOBAL_H
#define WORKFLOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKFLOW_LIBRARY)
#  define WORKFLOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WORKFLOWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKFLOW_GLOBAL_H
