#ifndef METADATA_DEFS_H_INCLUDED
#define METADATA_DEFS_H_INCLUDED

enum ActivityStatus {
    NONE_ACTIVITYSTATUS,
    READY_ACTIVITYSTATUS,
    ACTIVE_ACTIVITYSTATUS,
    CANCELLED_ACTIVITYSTATUS,
    ABORTING_ACTIVITYSTATUS,
    ABORTED_ACTIVITYSTATUS,
    COMPLETING_ACTIVITYSTATUS,
    COMPLETED_ACTIVITYSTATUS
};

enum ActivityType {
    TASK_ACTIVITYTYPE,
    SUBPROCESS_ACTIVITYTYPE
};

enum AssignTime {
    START_ASSIGNTIME,
    END_ASSIGNTIME
};

enum ConditionType {
    NONE_CONDITIONTYPE,
    EXPRESSION_CONDITIONTYPE,
    DEFAULT_CONDITIONTYPE
};

enum EventType {
    START_EVENTTYPE,
    END_EVENTTYPE,
    INTERMEDIATE_EVENTTYPE
};

enum LoopType {
    NONE_LOOPTYPE,
    STANDARD_LOOPTYPE,
    MULTIINSTANCE_LOOPTYPE
};

enum ParticipantType {
    ROLE_PARTICIPANTTYPE,
    ENTITY_PARTICIPANTTYPE
};

enum ProcessType {
    NONE_PROCESSTYPE,
    PRIVATE_PROCESSTYPE,
    ABSTRACT_PROCESSTYPE,
    COLLABORATION_PROCESSTYPE
};

enum PropertyType {
    INT_PROPERTYTYPE,
    STRING_PROPERTYTYPE,
    SET_PROPERTYTYPE
};

enum ConnectorType {
    TASK,
    EVENT
};

enum TaskType {
    SERVICE_TASKTYPE,
    RECEIVE_TASKTYPE,
    SEND_TASKTYPE,
    USER_TASKTYPE,
    SCRIPT_TASKTYPE,
    MANUAL_TASKTYPE,
    REFERENCE_TASKTYPE,
    NONE_TASKTYPE
};

enum Trigger {
    NONE_TRIGGER,
    MESSAGE_TRIGGER,
    TIMER_TRIGGER,
    RULE_TRIGGER,
    LINK_TRIGGER,
    MULTIPLE_TRIGGER
};

#endif // METADATA_DEFS_H_INCLUDED
