/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace djondb {

public enum EXPRESSION_TYPE {
  ET_CONSTANT,
  ET_SIMPLE,
  ET_BINARY,
  ET_UNARY
}

}
