/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sinco.designer.projecteditor;

import com.mxgraph.swing.examples.FreeGraphEditor;
import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;
import org.openide.windows.CloneableTopComponent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class JFATopWindowTopComponent extends CloneableTopComponent {

    private static JFATopWindowTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "JFATopWindowTopComponent";
    private FreeGraphEditor graphEditor;
    
    private JaguarProjectDataObject dataObject;

    public JFATopWindowTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(JFATopWindowTopComponent.class, "CTL_JFATopWindowTopComponent"));
        setToolTipText(NbBundle.getMessage(JFATopWindowTopComponent.class, "HINT_JFATopWindowTopComponent"));
        setLayout(new BorderLayout());
        graphEditor = new FreeGraphEditor();
        add(graphEditor, BorderLayout.CENTER);
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    JFATopWindowTopComponent(JaguarProjectDataObject dobj) {
        try {
            initComponents();
            setName(NbBundle.getMessage(JFATopWindowTopComponent.class, "CTL_JFATopWindowTopComponent"));
            setToolTipText(NbBundle.getMessage(JFATopWindowTopComponent.class, "HINT_JFATopWindowTopComponent"));
            setLayout(new BorderLayout());
            dataObject = dobj;
            graphEditor = new FreeGraphEditor();
            File file = new File(dobj.getPrimaryFile().getPath());
            graphEditor.setCurrentFile(file);
            add(graphEditor, BorderLayout.CENTER);
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized JFATopWindowTopComponent getDefault() {
        if (instance == null) {
            instance = new JFATopWindowTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the JFATopWindowTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized JFATopWindowTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(JFATopWindowTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof JFATopWindowTopComponent) {
            return (JFATopWindowTopComponent) win;
        }
        Logger.getLogger(JFATopWindowTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return JFATopWindowTopComponent.getDefault();
        }
    }
}
