/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class BSONParser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BSONParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BSONParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        djonwrapperJNI.delete_BSONParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BSONParser() {
    this(djonwrapperJNI.new_BSONParser(), true);
  }

  public static BSONObj parse(String sbson) {
    long cPtr = djonwrapperJNI.BSONParser_parse(sbson);
    return (cPtr == 0) ? null : new BSONObj(cPtr, false);
  }

  public static BSONArrayObj parseArray(String sbson) {
    long cPtr = djonwrapperJNI.BSONParser_parseArray(sbson);
    return (cPtr == 0) ? null : new BSONArrayObj(cPtr, false);
  }

}
