/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class ConnectionManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ConnectionManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ConnectionManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        djonwrapperJNI.delete_ConnectionManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConnectionManager() {
    this(djonwrapperJNI.new_ConnectionManager(), true);
  }

  public static Connection getConnection(String host) {
    long cPtr = djonwrapperJNI.ConnectionManager_getConnection__SWIG_0(host);
    return (cPtr == 0) ? null : new Connection(cPtr, false);
  }

  public static Connection getConnection(String host, int port) {
    long cPtr = djonwrapperJNI.ConnectionManager_getConnection__SWIG_1(host, port);
    return (cPtr == 0) ? null : new Connection(cPtr, false);
  }

  public static void releaseConnection(Connection conn) {
    djonwrapperJNI.ConnectionManager_releaseConnection(Connection.getCPtr(conn), conn);
  }

}
