/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public final class EXPRESSION_TYPE {
  public final static EXPRESSION_TYPE ET_CONSTANT = new EXPRESSION_TYPE("ET_CONSTANT");
  public final static EXPRESSION_TYPE ET_SIMPLE = new EXPRESSION_TYPE("ET_SIMPLE");
  public final static EXPRESSION_TYPE ET_BINARY = new EXPRESSION_TYPE("ET_BINARY");
  public final static EXPRESSION_TYPE ET_UNARY = new EXPRESSION_TYPE("ET_UNARY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EXPRESSION_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EXPRESSION_TYPE.class + " with value " + swigValue);
  }

  private EXPRESSION_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EXPRESSION_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EXPRESSION_TYPE(String swigName, EXPRESSION_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EXPRESSION_TYPE[] swigValues = { ET_CONSTANT, ET_SIMPLE, ET_BINARY, ET_UNARY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

