/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConnectionManagerWrapper */

#ifndef _Included_ConnectionManagerWrapper
#define _Included_ConnectionManagerWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConnectionManagerWrapper
 * Method:    getConnection
 * Signature: (Ljava/lang/String;)LConnectionWrapper;
 */
JNIEXPORT jobject JNICALL Java_ConnectionManagerWrapper_getConnection
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ConnectionManagerWrapper
 * Method:    releaseConnection
 * Signature: (LConnectionWrapper;)V
 */
JNIEXPORT void JNICALL Java_ConnectionManagerWrapper_releaseConnection
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
